version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: expense-postgres
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: expense-rabbitmq
    ports:
      - "5672:5672"     # conexão da aplicação
      - "15672:15672"   # painel web
    environment:
      RABBITMQ_DEFAULT_USER: expense_user
      RABBITMQ_DEFAULT_PASS: expense_pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data: